// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCthkPKRhSMCCy-1_eeaXy-4krhsmgpg28',
    appId: '1:367486571754:web:fab18d5ee48edc035a3393',
    messagingSenderId: '367486571754',
    projectId: 'notes-app-777bd',
    authDomain: 'notes-app-777bd.firebaseapp.com',
    storageBucket: 'notes-app-777bd.firebasestorage.app',
    measurementId: 'G-C3D2B0BN7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj183-kPjsZPh-p6tdhJUlWK9NNXsbHj8',
    appId: '1:367486571754:android:f9ce9ffee8b31fa95a3393',
    messagingSenderId: '367486571754',
    projectId: 'notes-app-777bd',
    storageBucket: 'notes-app-777bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7RwObAlllEVqGCxPbP4tMiBGkreCwEr4',
    appId: '1:367486571754:ios:fe62f8e81bc08eed5a3393',
    messagingSenderId: '367486571754',
    projectId: 'notes-app-777bd',
    storageBucket: 'notes-app-777bd.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7RwObAlllEVqGCxPbP4tMiBGkreCwEr4',
    appId: '1:367486571754:ios:fe62f8e81bc08eed5a3393',
    messagingSenderId: '367486571754',
    projectId: 'notes-app-777bd',
    storageBucket: 'notes-app-777bd.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCthkPKRhSMCCy-1_eeaXy-4krhsmgpg28',
    appId: '1:367486571754:web:02c8a30907dfd8065a3393',
    messagingSenderId: '367486571754',
    projectId: 'notes-app-777bd',
    authDomain: 'notes-app-777bd.firebaseapp.com',
    storageBucket: 'notes-app-777bd.firebasestorage.app',
    measurementId: 'G-LDHSWWV8TG',
  );

}